let currentSpeed=1;let currentExtraGap=0;function removeMarqueeDuplication(container){if(container.dataset.duplicated){const children=Array.from(container.children);const originalCount=children.length/2;container.innerHTML='';for(let i=0;i<originalCount;i++){container.appendChild(children[i])}
delete container.dataset.duplicated}}
class Marquee{constructor(container,speed,extraGap=0){this.container=container;this.speed=speed;this.extraGap=extraGap;this.offset=0;this.paused=!1;this.rafId=null;if(!this.container.dataset.duplicated){this.container.innerHTML+=this.container.innerHTML;this.container.dataset.duplicated='true'}
this.totalWidth=this.computeTotalWidth();this.handleMouseEnter=this.pause.bind(this);this.handleMouseLeave=this.resume.bind(this);if(!this.container.dataset.marqueeListenersAdded){this.container.addEventListener('mouseenter',this.handleMouseEnter);this.container.addEventListener('mouseleave',this.handleMouseLeave);this.container.dataset.marqueeListenersAdded='true'}
this.animate=this.animate.bind(this);this.animate()}
computeTotalWidth(){const children=Array.from(this.container.children);const originalCount=this.container.dataset.duplicated?children.length/2:children.length;if(originalCount<1)return 0;const originalItems=children.slice(0,originalCount);let totalWidth=0;originalItems.forEach(item=>{totalWidth+=item.getBoundingClientRect().width});const style=window.getComputedStyle(this.container);const gap=parseFloat(style.gap||style.columnGap||0);if(originalItems.length>1){totalWidth+=gap*(originalItems.length-1)}
totalWidth+=this.extraGap;return totalWidth}
animate(){if(!this.paused){this.offset-=this.speed;if(Math.abs(this.offset)>=this.totalWidth){this.offset+=this.totalWidth}
this.container.style.transform=`translateX(${this.offset}px)`}
this.rafId=requestAnimationFrame(this.animate)}
pause(){this.paused=!0}
resume(){this.paused=!1}
cancel(){if(this.rafId){cancelAnimationFrame(this.rafId);this.rafId=null}
this.container.removeEventListener('mouseenter',this.handleMouseEnter);this.container.removeEventListener('mouseleave',this.handleMouseLeave);delete this.container.dataset.marqueeListenersAdded}}
function setupMarquee(container,speed,extraGap=0){if(!container)return;if(container._marqueeInstance){container._marqueeInstance.speed=speed;container._marqueeInstance.extraGap=extraGap;return}
container._marqueeInstance=new Marquee(container,speed,extraGap)}
export function setupNichoButtons(){const nichoButtons=document.querySelectorAll('.btn-nicho');const nichoSections=document.querySelectorAll('.cards-servicos-nicho');nichoButtons.forEach(button=>{button.addEventListener('click',()=>{nichoButtons.forEach(btn=>btn.classList.remove('active'));button.classList.add('active');nichoSections.forEach(section=>{const marqueeContainer=section.querySelector('.cards-servicos-items');if(marqueeContainer&&marqueeContainer._marqueeInstance){marqueeContainer._marqueeInstance.cancel();marqueeContainer._marqueeInstance=null}
section.classList.remove('active')});const nicho=button.getAttribute('data-nicho');const targetSection=document.getElementById(nicho);if(targetSection){targetSection.classList.add('active')}
const marqueeContainer=targetSection?targetSection.querySelector('.cards-servicos-items'):null;if(window.innerWidth>=890){if(marqueeContainer){setupMarquee(marqueeContainer,currentSpeed,currentExtraGap)}}else{if(marqueeContainer){if(marqueeContainer._marqueeInstance){marqueeContainer._marqueeInstance.cancel();marqueeContainer._marqueeInstance=null}
marqueeContainer.style.transform='none';removeMarqueeDuplication(marqueeContainer)}}})})}
export function initMarqueeAllNichos(speed=1,extraGap=0){currentSpeed=speed;currentExtraGap=extraGap;setupNichoButtons();if(window.innerWidth>=890){const activeMarqueeContainers=document.querySelectorAll('.cards-servicos-nicho.active .cards-servicos-items',);activeMarqueeContainers.forEach(marqueeContainer=>{setupMarquee(marqueeContainer,speed,extraGap)})}
window.addEventListener('resize',()=>{const activeMarqueeContainer=document.querySelector('.cards-servicos-nicho.active .cards-servicos-items',);if(activeMarqueeContainer){if(window.innerWidth>=890){setupMarquee(activeMarqueeContainer,currentSpeed,currentExtraGap)}else{if(activeMarqueeContainer._marqueeInstance){activeMarqueeContainer._marqueeInstance.cancel();activeMarqueeContainer._marqueeInstance=null}
activeMarqueeContainer.style.transform='none';removeMarqueeDuplication(activeMarqueeContainer)}}})}